version: 2
jobs:
  build:
    working_directory: ~/repo
    parallelism: 1
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      # Machine Setup
      - checkout
      # Restore the dependency cache
      - restore_cache:
          keys:
            # This branch if available
            - v1-dep-{{ .Branch }}-
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      # Save dependency cache
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor/bundle
            - ~/virtualenvs
            - ~/.m2
            - ~/.ivy2
            - ~/.bundle
            - ~/.go_workspace
            - ~/.gradle
            - ~/.cache/bower
            # These cache paths were specified in the 1.0 config
            - ~/.android
            - ~/android
      # Test
      - run: ./gradlew build
      # Teardown
      - store_artifacts:
          name: Store test reports
          path: app/build/reports/tests
          destination: tests
      - store_artifacts:
          name: Store apk and other outputs
          path: app/build/outputs
          destination: outputs
      - store_artifacts:
          name: Store Lint report
          path: app/build/reports/lint-results.html
          destination: lint